version: '3.8'

services:

    nginx:
        image: nginx:stable-alpine
        container_name: ${CONTAINER_NAME_NGINX:-wp-web}
        ports:
            - "80:80"
        volumes:
            - ./devops/local/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./wordpress:/var/www/html
        working_dir: /var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "${LOCAL_DOMAIN:-wp.local}:host-gateway"
        depends_on:
            - php
            - mysql
        # networks:
        #     - wp-network

    mysql:
        image: mysql:8.0
        container_name: ${CONTAINER_NAME_MYSQL:-wp-db}
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        # networks:
        #     - wp-network

    php:
        container_name: ${CONTAINER_NAME_PHP:-wp-app}
        build:
            context: .
            dockerfile: devops/local/Dockerfile
        volumes:
            - ./wordpress:/var/www/html
            - ./devops/local/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /var/www/html
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        entrypoint: >
            sh -c "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html && php-fpm"
        # networks:
        #     - wp-network

volumes:
    dbdata:

# networks:
#     wp-network:
#         driver: bridge
